fixing run

diff --git a/cloudenv b/cloudenv
--- a/cloudenv
+++ b/cloudenv
@@ -24,13 +24,14 @@ cloudenv_usage() {
   echo
   # :command.usage_commands
   printf "Commands:\n"
-  echo "  login   Login to CloudEnv service"
-  echo "  init    Initialize a new project"
-  echo "  merge   Merge into CloudEnv"
-  echo "  edit    Edit an environmental variable file"
-  echo "  show    Show an environmental variable file"
-  echo "  push    Push an existing environmental variable file"
-  echo "  run     Run a command using some environmental variables"
+  echo "  login     Login to CloudEnv service"
+  echo "  init      Initialize a new project"
+  echo "  merge     Merge into CloudEnv"
+  echo "  edit      Edit an environmental variable file"
+  echo "  show      Show an environmental variable file"
+  echo "  push      Push an existing environmental variable file"
+  echo "  run       Run a command using some environmental variables"
+  echo "  upgrade   Upgrade the cloudenv cli"
   echo
 
   if [[ -n $long_usage ]]; then
@@ -307,7 +308,7 @@ cloudenv_run_usage() {
   echo
 
   printf "Usage:\n"
-  printf "  cloudenv run [ENVIRONMENT] [options]\n"
+  printf "  cloudenv run [ENVIRONMENT] [COMMAND]\n"
   printf "  cloudenv run --help | -h\n"
   echo
 
@@ -317,11 +318,7 @@ cloudenv_run_usage() {
     echo "  --help, -h"
     printf "    Show this help\n"
     echo
-    # :command.usage_flags
-    # :flag.usage
-    echo "  --command, -c COMMAND"
-    printf "    Name of the command to start\n"
-    echo
+
     # :command.usage_args
     printf "Arguments:\n"
     
@@ -330,13 +327,53 @@ cloudenv_run_usage() {
     printf "    Which environment should these variables be accessible in\n"
     printf "    Default: default\n"
     echo
+    
+    # :argument.usage
+    echo "  COMMAND"
+    printf "    Name of the command to start\n"
+    printf "    Default: default\n"
+    echo
 
     # :command.usage_examples
     printf "Examples:\n"
     
-    printf "  cloudenv run default --command your-app-cli-start-command\n"
-    printf "  cloudenv run staging --command your-app-cli-start-command\n"
-    printf "  cloudenv run production --command your-app-cli-start-command\n"
+    printf "  cloudenv run default your-app-cli-start-command\n"
+    printf "  cloudenv run staging your-app-cli-start-command\n"
+    printf "  cloudenv run production your-app-cli-start-command\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+cloudenv_upgrade_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "cloudenv upgrade - Upgrade the cloudenv cli\n"
+    echo 
+  else
+    printf "cloudenv upgrade - Upgrade the cloudenv cli\n"
+    echo 
+  fi
+
+  printf "Shortcut: u\n"
+  echo
+
+  printf "Usage:\n"
+  printf "  cloudenv upgrade\n"
+  printf "  cloudenv upgrade --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "Examples:\n"
+    
+    printf "  cloudenv upgrade\n"
     echo
 
   fi
@@ -615,19 +652,29 @@ cloudenv_show_command() {
   	exit
   fi
   
-  editor="${EDITOR:-nano}"
   bearer=`cat ~/.cloudenvrc`
   app=`head -1 .cloudenv-secret-key`
   secretkey=`tail -1 .cloudenv-secret-key`
   environment="${args[environment]}"
   tempdir="$(mktemp -d ~/.tmp.XXXXXXXX)"
   
-  curl -s -H "Authorization: Bearer $bearer" "https://app.cloudenv.com/api/v1/envs?name=$app&environment=$environment" > "$tempdir/cloudenv-edit-$environment-encrypted"
-  
-  if [ -s "$tempdir/cloudenv-edit-$environment-encrypted" ]
+  if [ "$environment" != "default" ]
   then
-  	openssl enc -a -aes-256-cbc -md sha512 -d -pass pass:"$secretkey" -in "$tempdir/cloudenv-edit-$environment-encrypted" -out "$tempdir/cloudenv-edit-$environment"
-  	cat "$tempdir/cloudenv-edit-$environment"
+  	curl -s -H "Authorization: Bearer $bearer" "https://app.cloudenv.com/api/v1/envs?name=$app&environment=default" > "$tempdir/cloudenv-show-default-encrypted"
+  
+  	if [ -s "$tempdir/cloudenv-show-default-encrypted" ]
+  	then
+  		openssl enc -a -aes-256-cbc -md sha512 -d -pass pass:"$secretkey" -in "$tempdir/cloudenv-show-default-encrypted" -out "$tempdir/cloudenv-show-default"
+  		cat "$tempdir/cloudenv-show-default"
+  	fi
+  fi
+  
+  curl -s -H "Authorization: Bearer $bearer" "https://app.cloudenv.com/api/v1/envs?name=$app&environment=$environment" > "$tempdir/cloudenv-show-$environment-encrypted"
+  
+  if [ -s "$tempdir/cloudenv-show-$environment-encrypted" ]
+  then
+  	openssl enc -a -aes-256-cbc -md sha512 -d -pass pass:"$secretkey" -in "$tempdir/cloudenv-show-$environment-encrypted" -out "$tempdir/cloudenv-show-$environment"
+  	cat "$tempdir/cloudenv-show-$environment"
   fi
   
   rm -rf "$tempdir"
@@ -714,11 +761,16 @@ cloudenv_run_command() {
   if [ -s "$tempdir/cloudenv-edit-$environment-encrypted" ]
   then
   	openssl enc -a -aes-256-cbc -md sha512 -d -pass pass:"$secretkey" -in "$tempdir/cloudenv-edit-$environment-encrypted" -out "$tempdir/cloudenv-edit-$environment"
-  	source "$tempdir/cloudenv-edit-$environment"
-  	"$command"
+  	bash -c "source '$tempdir/cloudenv-edit-$environment'; $command"
   fi
   
   rm -rf "$tempdir"
+}
+
+# :command.function
+cloudenv_upgrade_command() {
+  # :src/upgrade_command.sh
+  curl -Ls https://cloudenv.com/install.txt | sh
 }
 
 # :command.parse_requirements
@@ -792,6 +844,13 @@ parse_requirements() {
     action="run"
     shift
     cloudenv_run_parse_requirements "$@"
+    shift $#
+    ;;    
+  
+  upgrade | u )
+    action="upgrade"
+    shift
+    cloudenv_upgrade_parse_requirements "$@"
     shift $#
     ;;    
   
@@ -1164,18 +1223,6 @@ cloudenv_run_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-    # :flag.case
-    --command | -c )
-      if [[ $2 && $2 != -* ]]; then
-        args[--command]="$2"
-        shift
-        shift
-      else
-        printf "%s\n" "--command requires an argument: --command, -c COMMAND"
-        exit 1
-      fi
-      ;;
-  
   
     -* )
       printf "invalid option: %s\n" "$key"
@@ -1187,6 +1234,9 @@ cloudenv_run_parse_requirements() {
       if [[ ! ${args[environment]} ]]; then
         args[environment]=$1
         shift
+      elif [[ ! ${args[command]} ]]; then
+        args[command]=$1
+        shift
       else
         printf "invalid argument: %s\n" "$key"
         exit 1
@@ -1197,6 +1247,50 @@ cloudenv_run_parse_requirements() {
   done
   # :command.default_assignments
   [[ -n ${args[environment]} ]] || args[environment]="default"
+  [[ -n ${args[command]} ]] || args[command]="default"
+}
+
+# :command.parse_requirements
+cloudenv_upgrade_parse_requirements() {
+  # :command.fixed_flag_filter
+  case "$1" in
+  --version | -v )
+    version_command
+    exit
+    ;;
+  
+  --help | -h )
+    long_usage=yes
+    cloudenv_upgrade_usage
+    exit 1
+    ;;
+  
+  esac
+  # :command.environment_variables_filter
+  # :command.dependencies_filter
+  # :command.command_filter
+  action="upgrade"
+  # :command.required_args_filter
+  # :command.required_flags_filter
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+  
+    -* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+  
+    * )
+      # :command.parse_requirements_case
+      printf "invalid argument: %s\n" "$key"
+      exit 1
+      ;;
+  
+    esac
+  done
+  # :command.default_assignments
 }
 
 # :command.initialize
@@ -1273,6 +1367,14 @@ run() {
       cloudenv_run_usage
     else
       cloudenv_run_command
+    fi
+  
+  elif [[ $action == "upgrade" ]]; then
+    if [[ ${args[--help]} ]]; then
+      long_usage=yes
+      cloudenv_upgrade_usage
+    else
+      cloudenv_upgrade_command
     fi
   
   elif [[ ${args[--version]} ]]; then
