Adding source cli

diff --git a/cloudenv b/cloudenv
--- a/cloudenv
+++ b/cloudenv
@@ -28,6 +28,7 @@ cloudenv_usage() {
   echo "  init      Initialize a new project"
   echo "  merge     Merge into CloudEnv"
   echo "  edit      Edit an environmental variable file"
+  echo "  source    Provide a source for configuring environment variables"
   echo "  show      Show an environmental variable file"
   echo "  raw       Show raw encrypted data for an environment"
   echo "  decrypt   Decrypt a raw data dump"
@@ -188,6 +189,40 @@ cloudenv_edit_usage() {
   printf "Usage:\n"
   printf "  cloudenv edit [ENVIRONMENT]\n"
   printf "  cloudenv edit --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "Arguments:\n"
+    
+    # :argument.usage
+    echo "  ENVIRONMENT"
+    printf "    Which environment should these variables be accessible in\n"
+    printf "    Default: default\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+cloudenv_source_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "cloudenv source - Provide a source for configuring environment variables\n"
+    echo 
+  else
+    printf "cloudenv source - Provide a source for configuring environment variables\n"
+    echo 
+  fi
+
+  printf "Usage:\n"
+  printf "  cloudenv source [ENVIRONMENT]\n"
+  printf "  cloudenv source --help | -h\n"
   echo
 
   if [[ -n $long_usage ]]; then
@@ -751,6 +786,40 @@ cloudenv_edit_command() {
 }
 
 # :command.function
+cloudenv_source_command() {
+  # :src/source_command.sh
+  environment="${args[environment]}"
+  
+  check_logged_in
+  check_for_project
+  check_can_read_env
+  
+  IFS=$'\n'
+  re=^\s*[A-Za-z_][A-Za-z0-9_]*=
+  
+  if [[ "$environment" != "default" ]]
+  then
+    for line in $(get_env "default"); do
+      if [[ $line =~ $re ]]; then
+        echo "export $line"
+      else
+        echo "$line"
+      fi
+    done
+  fi
+  
+  for line in $(get_env "$environment"); do
+    if [[ $line =~ $re ]]; then
+      echo "export $line"
+    else
+      echo "$line"
+    fi
+  done
+  
+  rm -rf "$tempdir"
+}
+
+# :command.function
 cloudenv_show_command() {
   # :src/show_command.sh
   environment="${args[environment]}"
@@ -892,6 +961,13 @@ parse_requirements() {
     action="edit"
     shift
     cloudenv_edit_parse_requirements "$@"
+    shift $#
+    ;;    
+  
+  source )
+    action="source"
+    shift
+    cloudenv_source_parse_requirements "$@"
     shift $#
     ;;    
   
@@ -1150,6 +1226,55 @@ cloudenv_edit_parse_requirements() {
   # :command.dependencies_filter
   # :command.command_filter
   action="edit"
+  # :command.required_args_filter
+  # :command.required_flags_filter
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+  
+    -* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+  
+    * )
+      # :command.parse_requirements_case
+      if [[ ! ${args[environment]} ]]; then
+        args[environment]=$1
+        shift
+      else
+        printf "invalid argument: %s\n" "$key"
+        exit 1
+      fi
+      ;;
+  
+    esac
+  done
+  # :command.default_assignments
+  [[ -n ${args[environment]} ]] || args[environment]="default"
+}
+
+# :command.parse_requirements
+cloudenv_source_parse_requirements() {
+  # :command.fixed_flag_filter
+  case "$1" in
+  --version | -v )
+    version_command
+    exit
+    ;;
+  
+  --help | -h )
+    long_usage=yes
+    cloudenv_source_usage
+    exit 1
+    ;;
+  
+  esac
+  # :command.environment_variables_filter
+  # :command.dependencies_filter
+  # :command.command_filter
+  action="source"
   # :command.required_args_filter
   # :command.required_flags_filter
   # :command.parse_requirements_while
@@ -1475,7 +1600,7 @@ cloudenv_upgrade_parse_requirements() {
 
 # :command.initialize
 initialize() {
-  version="0.2.1"
+  version="0.2.2"
   long_usage=''
   set -e  
 
@@ -1719,6 +1844,14 @@ run() {
       cloudenv_edit_usage
     else
       cloudenv_edit_command
+    fi
+  
+  elif [[ $action == "source" ]]; then
+    if [[ ${args[--help]} ]]; then
+      long_usage=yes
+      cloudenv_source_usage
+    else
+      cloudenv_source_command
     fi
   
   elif [[ $action == "show" ]]; then
