Refactoring CLI

diff --git a/cloudenv b/cloudenv
--- a/cloudenv
+++ b/cloudenv
@@ -391,14 +391,22 @@ cloudenv_login_command() {
   # :src/login_command.sh
   locked=0
   ip_address=`curl -s ident.me`
-  read -p "Do you want to lock these login credentials to your current ip address $ip_address (this provides extra security on server deployments)? (N/y): " newkey
+  echo
+  ohai "Your current ip address is $ip_address"
+  echo
+  read -p "Do you want to firewall this API token to this IP address (enhanced security on servers)? (N/y): " newkey
+  echo
   if [ "$newkey" == "y" ]
   then
     locked=1
   fi
   
   readonly=0
-  read -p "Do you want these login credentials to be read-only? (N/y): " newkey
+  echo
+  ohai "CloudEnv can prevent writes from this computer"
+  echo
+  read -p "Do you want this API token to be read-only? (N/y): " newkey
+  echo
   if [ "$newkey" == "y" ]
   then
     readonly=1
@@ -468,7 +476,7 @@ cloudenv_login_command() {
   echo
   ohai "Please visit this url and login or register to authorize this computer: "
   echo
-  ohai "${tty_underline}`cat "$tempdir/cloudenv.auth-url"`${tty_reset}"
+  echo "${tty_underline}$(cat "$tempdir/cloudenv.auth-url")${tty_reset}"
   echo
   echo
   
@@ -491,7 +499,7 @@ cloudenv_login_command() {
     email="${ADDR[0]}"
     token="${ADDR[1]}"
     echo $token > ~/.cloudenvrc
-    ohai "You are now logged in as $email"
+    ohai "You are now logged in as ${tty_underline}$email${tty_reset}"
     echo
   fi
 }
@@ -501,56 +509,66 @@ cloudenv_init_command() {
   # :src/init_command.sh
   check_logged_in
   
+  environment="${args[environment]}"
+  
   if [ -f .cloudenv-secret-key ]
   then
-  	name=`head -1 .cloudenv-secret-key`
-  	secretkey=`head -2 .cloudenv-secret-key | tail -1`
-  	environment="default"
+  	echo
   	warn "Already found an existing CloudEnv project in $PWD/.cloudenv-secret-key"
   	echo
   	read -p "Generate a new secret key for this project? (N/y): " newkey
+  	echo	
   	if [ "$newkey" == "y" ]
   	then
-  		curl -s -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/envs?app=$name&environment=$environment&version=$version&lang=cli" > "$tempdir/cloudenv-edit"
-  		if [ -s "$tempdir/cloudenv-edit" ]
+  		get_env "default" > "$tempdir/cloudenv-edit-decrypted"
+  		if [ -s "$tempdir/cloudenv-edit-decrypted" ]
   		then
-  			openssl enc -aes-256-cbc -md sha512 -d -pass pass:"$secretkey" -in "$tempdir/cloudenv-edit" -out "$tempdir/cloudenv-edit-decrypted"
   			head -1 .cloudenv-secret-key > .cloudenv-secret-key-new
   			base64 < /dev/urandom | tr -d 'O0Il1+/' | head -c 256 | tr '\n' '1' >> .cloudenv-secret-key-new
   			echo >> .cloudenv-secret-key-new
   			mv .cloudenv-secret-key-new .cloudenv-secret-key
   			sha=`openssl dgst -sha256 .cloudenv-secret-key`
-  		    read -ra ADDR <<< "$sha"
-  			app=`curl -s -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/apps?name=$name&sha=${ADDR[1]}"`
+  		  read -ra ADDR <<< "$sha"
+  			status=`curl -s --data-urlencode "name=$name" --data-urlencode "sha=${ADDR[1]}" --data-urlencode "version=$version" --data-urlencode "lang=cli" -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/apps"`
   			secretkey=`head -2 .cloudenv-secret-key | tail -1`
-  			openssl enc -aes-256-cbc -md sha512 -pass pass:"$secretkey" -in "$tempdir/cloudenv-edit-decrypted" -out "$tempdir/cloudenv-edit"
-  			curl -s -H "Authorization: Bearer $bearer" -F "data=@$tempdir/cloudenv-edit" "$BASE_URL/api/v1/envs?app=$name&environment=$environment&version=$version&lang=cli"
+  			upload_env "$tempdir/cloudenv-edit-decrypted"
   		else
   			warn "Couldn't find this app in CloudEnv, try deleting $PWD/.cloudenv-secret-key and starting over"
+  			echo
+  			rm -rf "$tempdir/cloudenv-edit*"
   			exit
   		fi
-  		rm "$tempdir/cloudenv-edit*"
-  		if [ "$app" != 200 ]
+  		rm -rf "$tempdir/cloudenv-edit*"
+  		if [ "$status" != 200 ]
   		then
-  			echo
-  			warn "ERROR ($app): I'm sorry but you do not have access to this app. If you believe this is in error, please contact another team member."
+  			warn "ERROR ($status): I'm sorry but you do not have access to this app. If you believe this is in error, please contact another team member."
   		else
-  			echo
   			ohai "SUCCESS: New encryption key generated"
   			echo
-  			ohai "You need to distribute $PWD/.cloudenv-secret-key to all your team members and servers"
+  			ohai "You need to re-distribute the following file to all your team members and deployment servers"
+  			echo
+  			echo "$PWD/.cloudenv-secret-key"
+  			echo
   		fi
   	fi
   else
-  	account_number=$(curl -s -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/accounts.txt?version=$version&lang=cli" | wc -l)
+  	account_number=$(curl -s -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/accounts.txt?version=$version&lang=cli" | wc -l | xargs)
   
   	if [ "$account_number" -gt "1" ]
   	then
-  		ohai "Which account would you like to use from the following?"
+  		echo
+  		ohai "Which account would you like this app to be associated with?"
+  		echo
   		curl -s -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/accounts.txt?version=$version&lang=cli"
+  		echo
   		read -p "Account number (1-$account_number): " account_number
   		echo
   		ohai "Got it, now let's name your app."
+  		echo
+  	else
+  		echo
+  		ohai "Let's name your app."
+  		echo
   	fi
   
   	read -p "Name of App: " name
@@ -561,14 +579,15 @@ cloudenv_init_command() {
   	# finally, lowercase with TR
   	slug=`echo -n $slug | tr A-Z a-z`
   
-  	app=`curl -s --data-urlencode "slug=$slug" --data-urlencode "name=$name" --data-urlencode "version=$version" --data-urlencode "lang=cli" --data-urlencode "account_number=$account_number" -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/apps"`
-  	if [ "$app" == 401 ]
+  	status=`curl -s --data-urlencode "slug=$slug" --data-urlencode "name=$name" --data-urlencode "version=$version" --data-urlencode "lang=cli" --data-urlencode "account_number=$account_number" -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/apps"`
+  	if [ "$status" == 401 ]
   	then
   		echo
   		warn "ERROR (401): This app name already exists, please choose a different one and try again."
+  		rm .cloudenv-secret-key
   		exit
   	fi
-  	if [ "$app" == 200 ]
+  	if [ "$status" == 200 ]
   	then
   		echo
   		warn "ERROR (200): This app name already exists."
@@ -583,29 +602,27 @@ cloudenv_init_command() {
   	sha=`openssl dgst -sha256 .cloudenv-secret-key`
     read -ra ADDR <<< "$sha"
   	curl -s -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/apps?account_number=$account_number&name=$name&slug=$slug&sha=${ADDR[1]}&version=$version&lang=cli" > "$tempdir/cloudenv-app"
-  	if [ "$app" == 201 ]
+  	if [ "$status" == 201 ]
   	then
   		echo
   		ohai "SUCCESS: You have created the app '$name' in CloudEnv"
   		echo
-  		ohai "You need to distribute $PWD/.cloudenv-secret-key to all your team members and servers"
+  		ohai "You need to distribute the following file to all your team members and deployment servers"
+  		echo
+  		echo "$PWD/.cloudenv-secret-key"
+  		echo
   	else
-  		if [ "$app" == 401 ]
+  		if [ "$status" == 401 ]
   		then
   			echo
-  			warn "ERROR ($app): Authentication error. Please run: cloudenv login"
+  			warn "ERROR ($status): Authentication error. Please run: cloudenv login"
+  			rm .cloudenv-secret-key
   			exit
   		else
-  			if [ "$app" == 404 ]
-  			then
-  				echo
-  				warn "ERROR ($app): The CLI does not yet support accounts that are part of multiple organizations, please create this app at app.cloudenv.com"
-  				exit
-  			else
-  				echo
-  				warn "ERROR ($app): There was a problem creating app '$name' with slug '$slug'. Please try to create the app at app.cloudenv.com"
-  				exit
-  			fi
+  			echo
+  			warn "ERROR ($status): There was a problem creating app '$name' with slug '$slug'. Please try to create the app at app.cloudenv.com"
+  			rm .cloudenv-secret-key
+  			exit
   		fi
   	fi
   fi
@@ -623,54 +640,27 @@ cloudenv_merge_command() {
 # :command.function
 cloudenv_edit_command() {
   # :src/edit_command.sh
-  if [ ! -f ~/.cloudenvrc ]
-  then
-  	echo
-  	warn "Not logged in"
-  	echo
-  	ohai "Please run: cloudenv login"
-  	echo
-  	exit
-  fi
+  check_logged_in
+  check_for_project
   
-  if [ ! -f .cloudenv-secret-key ]
-  then
-  	echo
-  	warn "Couldn't find a cloudenv project in $PWD/.cloudenv-secret-key"
-  	echo
-  	ohai "Please run: cloudenv init"
-  	echo
-  	ohai "Or cd into the root directory of your app to make env edits"
-  	echo
-  	exit
-  fi
-  
-  editor="${EDITOR:-nano}"
-  bearer=`cat ~/.cloudenvrc | tr -d " \t\n\r"`
-  app=`head -1 .cloudenv-secret-key`
-  secretkey=`head -2 .cloudenv-secret-key | tail -1`
   environment="${args[environment]}"
   
-  curl -s -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/envs?name=$app&environment=$environment&version=$version&lang=cli" > "$tempdir/cloudenv-edit-$environment-encrypted"
-  
-  if [ -s "$tempdir/cloudenv-edit-$environment-encrypted" ]
-  then
-  	openssl enc -a -aes-256-cbc -md sha512 -d -pass pass:"$secretkey" -in "$tempdir/cloudenv-edit-$environment-encrypted" -out "$tempdir/cloudenv-edit-$environment" 2> /dev/null
-  else
-  	touch "$tempdir/cloudenv-edit-$environment"
-  fi
+  get_env "$environment" > "$tempdir/cloudenv-edit-$environment"
   
   cp "$tempdir/cloudenv-edit-$environment" "$tempdir/cloudenv-orig-$environment"
   "$editor" "$tempdir/cloudenv-edit-$environment"
   
+  echo
+  
   if cmp --silent "$tempdir/cloudenv-edit-$environment" "$tempdir/cloudenv-orig-$environment"
   then
-  	echo "No changes detected"
+  	warn "No changes detected"
   else
-  	openssl enc -a -aes-256-cbc -md sha512 -pass pass:"$secretkey" -in "$tempdir/cloudenv-edit-$environment" -out "$tempdir/cloudenv-edit-$environment-encrypted" 2> /dev/null
-  
-  	curl -s -H "Authorization: Bearer $bearer" -F "data=@$tempdir/cloudenv-edit-$environment-encrypted" "$BASE_URL/api/v1/envs?name=$app&environment=$environment&version=$version&lang=cli" > /dev/null
+  	upload_env "$tempdir/cloudenv-edit-$environment"
+  	ohai "Your changes to $app ($environment environment) have been uploaded"
   fi
+  
+  echo
   
   rm -rf "$tempdir"
 }
@@ -681,26 +671,14 @@ cloudenv_show_command() {
   check_logged_in
   check_for_project
   
+  environment="${args[environment]}"
+  
   if [ "$environment" != "default" ]
   then
-  	curl -s -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/envs?name=$app&environment=default&version=$version&lang=cli" > "$tempdir/cloudenv-show-default-encrypted"
-  
-  	if [ -s "$tempdir/cloudenv-show-default-encrypted" ]
-  	then
-  		openssl enc -a -aes-256-cbc -md sha512 -d -pass pass:"$secretkey" -in "$tempdir/cloudenv-show-default-encrypted" 2> /dev/null
-  	else
-  		echo "# ${tty_red}Warning${tty_reset}: Couldn't get the $environment environment from $app"
-  	fi
+  	get_env "default"
   fi
   
-  curl -s -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/envs?name=$app&environment=$environment&version=$version&lang=cli" > "$tempdir/cloudenv-show-$environment-encrypted"
-  
-  if [ -s "$tempdir/cloudenv-show-$environment-encrypted" ]
-  then
-  	openssl enc -a -aes-256-cbc -md sha512 -d -pass pass:"$secretkey" -in "$tempdir/cloudenv-show-$environment-encrypted" 2> /dev/null
-  else
-  	echo "# ${tty_red}Warning${tty_reset}: Couldn't get the $environment environment from $app"
-  fi
+  get_env "$environment"
   
   rm -rf "$tempdir"
 }
@@ -712,15 +690,21 @@ cloudenv_push_command() {
   check_for_project
   
   file="${args[file]}"
+  environment="${args[environment]}"
+  
+  echo
   
   if [ -f "$file" ]
   then
-  	openssl enc -a -aes-256-cbc -md sha512 -pass pass:"$secretkey" -in "$file" -out "$tempdir/cloudenv-edit-$environment-encrypted" 2> /dev/null
-  	curl -s -H "Authorization: Bearer $bearer" -F "data=@$tempdir/cloudenv-edit-$environment-encrypted" "$BASE_URL/api/v1/envs?name=$app&environment=$environment" > /dev/null
+  	upload_env "$file"
   	ohai "Environment $environment in app $app has been updated"
   else
-  	warn "File $file does not exist"
+  	warn "File '$file' does not exist"
+  	echo
+  	echo "Usage: cloudenv push [environment] [filename]"
   fi
+  
+  echo
   
   rm -rf "$tempdir"
 }
@@ -732,16 +716,11 @@ cloudenv_run_command() {
   check_for_project
   
   command="${args[command]}"
+  environment="${args[environment]}"
   
-  curl -s -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/envs?name=$app&environment=$environment&version=$version&lang=cli" > "$tempdir/cloudenv-edit-$environment-encrypted"
+  get_env "$environment" > "$tempdir/cloudenv-edit-$environment"
   
-  if [ -s "$tempdir/cloudenv-edit-$environment-encrypted" ]
-  then
-  	openssl enc -a -aes-256-cbc -md sha512 -d -pass pass:"$secretkey" -in "$tempdir/cloudenv-edit-$environment-encrypted" -out "$tempdir/cloudenv-edit-$environment" 2> /dev/null
-  	bash -c "source '$tempdir/cloudenv-edit-$environment'; rm -rf $tempdir; $command"
-  else
-  	bash -c "$command"
-  fi
+  bash -c "source '$tempdir/cloudenv-edit-$environment'; rm -rf $tempdir; $command"
   
   rm -rf "$tempdir"
 }
@@ -1290,10 +1269,17 @@ initialize() {
   
   tempdir=$(mktemp -d)
   editor="${EDITOR:-nano}"
-  bearer=`cat ~/.cloudenvrc | tr -d " \t\n\r"`
-  app=`head -1 .cloudenv-secret-key`
-  secretkey=`head -2 .cloudenv-secret-key | tail -1`
-  environment="${args[environment]}"
+  
+  if [ -f ~/.cloudenvrc ]
+  then
+    bearer=`cat ~/.cloudenvrc | tr -d " \t\n\r"`
+  fi
+  
+  if [ -f .cloudenv-secret-key ]
+  then
+    app=`head -1 .cloudenv-secret-key`
+    secretkey=`head -2 .cloudenv-secret-key | tail -1`
+  fi
   
   # string formatters
   if [[ -t 1 ]]; then
@@ -1362,6 +1348,64 @@ initialize() {
     fi
   }
   
+  check_can_read_env() {
+    env=${1:-default}
+    curl -s -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/apps?name=$app&environment=$env&version=$version&lang=cli"
+  }
+  
+  check_can_write_env() {
+    env=${1:-default}
+    curl -s -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/envs?name=$app&environment=$env&version=$version&lang=cli"
+  }
+  
+  expand_tilde()
+  {
+      local tilde_re='^(~[A-Za-z0-9_.-]*)(.*)'
+      local path="$*"
+      local pathSuffix=
+  
+      if [[ $path =~ $tilde_re ]]
+      then
+          # only use eval on the ~username portion !
+          path=$(eval echo ${BASH_REMATCH[1]})
+          pathSuffix=${BASH_REMATCH[2]}
+      fi
+  
+      echo "${path}${pathSuffix}"
+  }
+  
+  get_encrypted_env() {
+    env=${1:-default}
+    curl -s -H "Authorization: Bearer $bearer" "$BASE_URL/api/v1/envs?name=$app&environment=$env&version=$version&lang=cli"
+  }
+  
+  get_env() {
+    env=${1:-default}
+    encrypted_file=$(mktemp)
+    output_file=$(mktemp)
+    get_encrypted_env $env > "$encrypted_file"
+  
+    if [ -s "$encrypted_file" ]
+    then
+      bash -c "$(openssl enc -a -aes-256-cbc -md sha512 -d -pass pass:"$secretkey" -in "$encrypted_file" -out "$output_file" 2> /dev/null)"
+    fi
+  
+    rm -rf "$encrypted_file"
+    cat "$output_file"
+    rm -rf "$output_file"
+  }
+  
+  encrypt_env() {
+    openssl enc -a -aes-256-cbc -md sha512 -pass pass:"$secretkey" -in "$1" -out "$2" 2> /dev/null
+  }
+  
+  upload_env() {
+    encrypted_file=$(mktemp)
+    encrypt_env "$1" "$encrypted_file" "$secretkey"
+    curl -s -H "Authorization: Bearer $bearer" -F "data=@$encrypted_file" "$BASE_URL/api/v1/envs?name=$app&environment=$environment&version=$version&lang=cli" > /dev/null
+    rm -rf "$encrypted_file"
+  }
+  
   getc() {
     local save_state
     save_state=$(/bin/stty -g)
@@ -1380,18 +1424,14 @@ initialize() {
     [[ "${1%.*}" -lt "${2%.*}" ]] || [[ "${1%.*}" -eq "${2%.*}" && "${1#*.}" -lt "${2#*.}" ]]
   }
   
-  if ! command -v curl >/dev/null; then
-      abort "$(cat <<EOABORT
-  You must install cURL before using cloudenv
-  EOABORT
-  )"
+  if ! command -v curl >/dev/null
+  then
+    abort "You must install curl before using cloudenv"
   fi
   
-  if ! command -v openssl >/dev/null; then
-      abort "$(cat <<EOABORT
-  You must install openssl before using cloudenv
-  EOABORT
-  )"
+  if ! command -v openssl >/dev/null
+  then
+    abort "You must install openssl before using cloudenv"
   fi
 }
 
